//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApiChaflaFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpleadoActividad
    {
        public int idEmpActivid { get; set; }
        public int idempleado { get; set; }
        public string nombreEmpleado { get; set; }
        public string actividad { get; set; }
        public System.DateTime fechaInicio { get; set; }
        public System.DateTime fechafin { get; set; }
        public int estado { get; set; }
    }
}
